openapi: 3.0.3

info:
  title: "Captcha Service"
  description: "Generates and validates captchas"
  version: "1.0"

servers:
  - url: http://localhost:3000/v1
  - url: https://nb-captcha-api.herokuapp.com/v1

paths:
  /captchas:
    post:
      summary: "Generates a new captcha"
      responses:
        '201':
          description: "Captcha generated"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/id'
                  jpegBase64:
                    type: string
                    format: base64

  /captchas/{id}:
    put:
      summary: "Validates a captcha"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: '#/components/schemas/id'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
      responses:
        '200':
          description: "Correct answer"
        '401':
          description: "Wrong answer"

components:
  schemas:
    id:
      type: string
      format: uuid
