name: Deploy frontend to Heroku

on:
  push:
    branches:
      - master
    #paths:
    #  - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_FRONTEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "frontend"
          usedocker: true
          docker_build_args: |
            VITE_API_URL
        env:
          VITE_API_URL: https://${{secrets.HEROKU_APP_NAME_API}}.herokuapp.com
