name: Test api

on:
  push:
    paths:
      #- 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
